title: Jason Xiao's Blog
email: xiaoyao8823@gmail.com
description: coding, gaming, photographing, loving...
author: Jason Xiao
baseurl: "/bboylilshaw.github.io"
url: "https://bboylilshaw.github.io"

# Social Profiles
twitter_username: bboylilshaw
github_username: bboylilshaw
instagram_username: bboylilshaw
linkedin_username: bboylilshaw

# Add your google-analytics ID here to activate google analytics
# google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
